SELECT * FROM USER_TABLES;

CREATE TABLE BOARD(
	NUM INT PRIMARY KEY,
	TITLE VARCHAR(15) NOT NULL,
	CONTENT VARCHAR(30) NOT NULL,
	WRITER VARCHAR(15) NOT NULL,
	CNT INT DEFAULT 0 -- 조회수
);

SELECT * FROM BOARD;

UPDATE BOARD SET TITLE = '안녕' WHERE NUM = 4;
UPDATE BOARD SET TITLE='제' WHERE NUM <= 5;
DELETE FROM BOARD WHERE NUM = 1;
-- SQL은 문법오류가 아니라면 전부 t
-- 대상이 없을 때, 0 row 
-- 대상이 있을 때, 1 row 혹은 N rows

INSERT INTO BOARD VALUES (1, '제목', '내용', '작성자', 0);
--INSERT INTO BOARD VALUES(2, '제목2', '내용2', '작성자2');
--INSERT INTO BOARD (NUM, TITLE, CONTENT, WRITER) VALUES (2, '제목2', '내용2', '작성자2');
INSERT INTO BOARD (NUM, TITLE, CONTENT, WRITER) VALUES ((SELECT NVL(MAX(NUM), 0) + 1 FROM BOARD), '제목', '내용', '작성자');
INSERT INTO BOARD VALUES((SELECT NVL(MAX(NUM),0)+1 FROM BOARD),'제목','내용','작성자',0);

