SELECT * FROM USER_TABLES;
SELECT * FROM MEMBER;

 -- AS(ALIAS) : 별칭 지정
SELECT NUM AS 주민번호 FROM MEMBER;
SELECT NUM AS 주민번호 FROM MEMBER ORDER BY NUM DESC; // 내림차순

-- || 연결 연산자
SELECT NAME, AGE || '세' AS "주민 번호" FROM MEMBER;

-- DISTINCT 중복값 제거
SELECT DISTINCT NAME FROM MEMBER;

-- ★★★★ SQL 실행 순서
-- FROM > WHERE > SELECT

SELECT NUM, NAME AS "이름", AGE AS "나이" FROM MEMBER WHERE AGE >= 25;
-- SELECT NUM, NAME AS "이름", AGE AS "나이" FROM MEMBER WHERE "나이" >= 25;
-- 별칭 서정이 WHERE 조건절 이후에 진행됨

-- BETWEEN 1 AND 2 : 1과 2 사이
SELECT AGE FROM MEMBER WHERE AGE BETWEEN 23 AND 40;

-- LIKE
SELECT NAME FROM MEMBER WHERE NAME LIKE '임%'; -- NAME이 임으로 시작하는
SELECT NAME FROM MEMBER WHERE NAME LIKE '%동'; -- NAME이 동로 끝나는
SELECT NAME FROM MEMBER WHERE NAME LIKE '%길%'; -- NAME에 길이 들어가는

-- COUNT()
-- SUBSTR()
-- LENGTH()
-- REPLACE()